[env]
_.path = ["{{config_root}}/bin"]

# Database configuration
PGDATABASE = "logger4life_dev"

# Tern migration configuration
TERN_CONFIG = "postgresql/tern.conf"
TERN_MIGRATIONS = "postgresql/migrations"

[tools]
fd = "latest"
go = '1.26.4'
nodejs = '24.13.0'
rg = "latest"
ruby = '4.0.3'
watchexec = "latest"

"github:jackc/tern" = "2.4.1"
"github:jackc/verna" = "0.5.1"
"go:golang.org/x/tools/cmd/goimports" = "latest"
