import adapter from '@sveltejs/adapter-static';
import { sveltekit } from '@sveltejs/kit/vite';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'vite';

// Ports come from this worktree's allocation (.port-tamer.env, generated by
// port-tamer). The fallbacks only apply when Vite is started outside the
// development stack.
const port = Number(process.env.VITE_PORT ?? 5173);
const backendURL = process.env.BACKEND_URL ?? `http://localhost:${process.env.BACKEND_PORT ?? 4000}`;

export default defineConfig({
	plugins: [
		tailwindcss(),
		sveltekit({
			adapter: adapter({
				pages: 'build/assets',
				assets: 'build/assets',
				fallback: 'index.html',
				precompress: true
			}),
			// Preserve Kit 2's disabled deployment polling.
			version: { pollInterval: 0 }
		})
	],
	server: {
		host: process.env.VITE_HOST ?? '127.0.0.1',
		port,
		// Never drift off the allocated port: the rest of the worktree has it
		// persisted, so a silent move would leave stale URLs everywhere.
		strictPort: true,
		proxy: {
			'/api': {
				target: backendURL,
				changeOrigin: true
			}
		}
	}
});
