import { sveltekit } from '@sveltejs/kit/vite';
import tailwindcss from '@tailwindcss/vite';
import { compression } from 'vite-plugin-compression2';
import { defineConfig } from 'vite';

// Ports come from this worktree's allocation (.dev/ports.env, generated by
// scripts/devports). The fallbacks only apply when Vite is started outside the
// development stack.
const port = Number(process.env.VITE_PORT ?? 5173);
const backendURL = process.env.BACKEND_URL ?? `http://localhost:${process.env.BACKEND_PORT ?? 4000}`;

export default defineConfig({
	plugins: [tailwindcss(), sveltekit(), compression({ algorithms: ['gzip', 'brotliCompress'] })],
	server: {
		host: process.env.VITE_HOST ?? '127.0.0.1',
		port,
		// Never drift off the allocated port: the rest of the worktree has it
		// persisted, so a silent move would leave stale URLs everywhere.
		strictPort: true,
		proxy: {
			'/api': {
				target: backendURL,
				changeOrigin: true
			}
		}
	}
});
